#!/bin/sh
set +e +x

if : Dependencies; then
	if test x"$GIT" == x""
	then
		GIT="$(which git)"
	fi

	if test x"$PYTHON" == x""
	then
		PYTHON="$(which python3)"
	fi

	export GIT PYTHON
fi

if : Test Environment; then
	SRC="$(cd "$(dirname "$0")"; pwd)"
	SCRIPT="$SRC/$(basename "$0")"
	WS="$(mktemp -d)"
	export SRC SCRIPT WS
fi

log ()
{
	echo >&2 "$@"
}

Test ()
{
	if test "$@"
	then
		return 0
	else
		log "-> $TEST: failed" '( absurdity test' "$@" ')'
		exit 1
	fi
}

LG ()
{
	# Repository initialization.
	"$GIT" 2>&1 "$@" | sed 's/^/test-repository: /'
}

GS ()
{
	(set -o pipefail
	"$PYTHON" 2>&1 "$SRC/git-select.py" "$@" | sed 's/^/git-select: /')
}

seal ()
{
	export TEST="$1"
	local tmp="$(mktemp -d)"
	(cd "$tmp" || exit
		if ("$1")
		then
			log "-> $TEST: passed"
		else
			:
		fi
	)
}

test_sole_resource ()
{
	# Citing sole data file.
	GS "$TR" main data-file
	Test -e data-file -a x"$(cat data-file)" = x"file-content-1"
}

test_resource_set ()
{
	# Citing multiple files, maintaining directory structure.
	GS "$TR" main data-file dir/data-file
	Test -e data-file -a x"$(cat data-file)" = x"file-content-1"
	Test -e dir/data-file -a x"$(cat dir/data-file)" = x"file-content-2"
}

test_resource_tree ()
{
	# Citing a directory.
	GS "$TR" main dir
	Test ! -e data-file
	Test -e dir/data-file -a x"$(cat dir/data-file)" = x"file-content-2"
	Test -e dir/sub/data-file -a x"$(cat dir/sub/data-file)" = x"file-content-3"
}

test_remapped_path ()
{
	# Remap a sole data file.
	GS "$TR" main dir/sub/data-file/./df
	Test -e df -a x"$(cat df)" = x"file-content-3"
}

test_remapped_resource_set ()
{
	# Citing multiple files, maintaining directory structure.
	GS "$TR" main data-file/./df1 dir/data-file/./df2
	Test -e df1 -a x"$(cat df1)" = x"file-content-1"
	Test -e df2 -a x"$(cat df2)" = x"file-content-2"
}

test_remapped_subdirectory ()
{
	# Remap a subdirectory.
	GS "$TR" main dir/sub//./d

	# Selected dir/sub; only contains data-file(3)
	Test -d d
	Test -e d/data-file -a x"$(cat d/data-file)" = x"file-content-3"
}

test_remapped_directory ()
{
	# Remap a root directory.
	GS "$TR" main dir/./rd

	# Selected dir/sub; only contains data-file(3)
	Test -d rd -a -d rd/sub
	Test -e rd/data-file -a x"$(cat rd/data-file)" = x"file-content-2"
	Test -e rd/sub/data-file -a x"$(cat rd/sub/data-file)" = x"file-content-3"
}

test_remapped_leading_path ()
{
	# Remap the leading path of a data-file using a trailing slash.
	GS "$TR" main dir/sub/data-file/./local-dir/
	Test -d local-dir
	Test -e local-dir/data-file -a x"$(cat local-dir/data-file)" = x"file-content-3"
}

test_no_such_repository ()
{
	GS "$TR/../fs-void" main data-file
	r=$?
	Test ! -e data-file
	Test $r -ne 0
}

test_no_such_snapshot ()
{
	GS "$TR" no-such-commit data-file
	r=$?
	Test ! -e data-file
	Test $r -ne 0
}

test_no_such_resource ()
{
	GS "$TR" main no-such-data-file
	r=$?
	Test ! -e no-such-data-file
	Test $r -ne 0
}

reveal ()
{
	# Check git-select features using $TR.
	for tid in $(sed -n 's/^\(test_.*\) ()$/\1/p' < "$SCRIPT")
	do
		(seal $tid)
	done
}

mkfixture ()
{
	set -e
	LG init -b main "$1"
	cd "$1"
	mkdir -p dir/sub/empty
	echo "file-content-1" >data-file
	echo "file-content-2" >dir/data-file
	echo "file-content-3" >dir/sub/data-file
	LG add dir data-file
	LG commit -m "sole" .
}

(cd "$WS"
	# Setup test repository.
	TR="$(pwd)/repo"
	PCACHE="$(pwd)/test-cache"
	log "=>" "$SRC/git-select.py" "$GIT" "$PYTHON"

	(mkfixture "$TR")

	# Check git-select features using $TR.
	log '=> [temporary-cache]'
	unset GIT_SELECT_CACHE
	reveal

	export GIT_SELECT_CACHE="$PCACHE"
	log "=> [persistent-cache $GIT_SELECT_CACHE]"
	reveal
)
